// ============================================================================
// gitClient.js — Handles all Git operations via shell commands.
//
// Production change vs. local version:
//   init() now accepts an optional `githubToken` parameter. When provided,
//   it embeds the token into the HTTPS clone URL so git can authenticate
//   without an interactive prompt — required on Render (no stored credentials).
//
//   URL format:  https://<token>@github.com/owner/repo.git
//
// The key trick: we use --date and GIT_COMMITTER_DATE to set BOTH the
// author date and committer date to the original LeetCode submission time.
// This makes GitHub's contribution graph show green squares on the correct days.
// ============================================================================

import { execSync } from 'child_process';
import fs   from 'fs';
import path from 'path';

const REPO_DIR = 'codesync_repo';

/**
 * getRepoPath — Returns the absolute path to the cloned repo directory.
 */
export function getRepoPath() {
  return path.resolve(process.cwd(), REPO_DIR);
}

/**
 * buildAuthUrl — Injects a GitHub token into an HTTPS clone URL.
 *
 * Input:  repoUrl (string)    — e.g. "https://github.com/user/repo.git"
 *         token   (string|null) — GitHub PAT or OAuth token
 * Output: authenticated URL, or original URL if no token / SSH URL
 *
 * Only modifies https:// URLs. SSH URLs (git@github.com) are left unchanged
 * because they use key-based auth and don't support token embedding.
 */
function buildAuthUrl(repoUrl, token) {
  if (!token || !repoUrl.startsWith('https://')) return repoUrl;
  // Strip any existing credentials to avoid double-embedding
  return repoUrl.replace('https://', `https://${token}@`);
}

/**
 * init — Clones the target Git repository into a local folder.
 *
 * Input:  repoUrl (string)     — the Git remote URL (HTTPS or SSH)
 *         token   (string|null) — GitHub token for HTTPS auth (production)
 * Output: none (creates the folder on disk)
 */
export function init(repoUrl, token = null) {
  const repoPath  = getRepoPath();
  const cloneUrl  = buildAuthUrl(repoUrl, token);

  // Clean up any leftover folder from a previous run
  if (fs.existsSync(repoPath)) {
    console.log('Cleaning up leftover repo folder from previous run...');
    fs.rmSync(repoPath, { recursive: true, force: true });
  }

  console.log(`Cloning into ${REPO_DIR}...`);
  // Use the authenticated URL for cloning but don't log it (contains the token)
  execSync(`git clone "${cloneUrl}" "${REPO_DIR}"`, {
    stdio: 'inherit',
  });

  // Configure a local git user so commits work on machines without a global
  // user.name / user.email set up (e.g. Render's ephemeral containers).
  execSync('git config user.email "codesync@local.dev"', { cwd: REPO_DIR, stdio: 'pipe' });
  execSync('git config user.name "CodeSync"',            { cwd: REPO_DIR, stdio: 'pipe' });

  // If we have a token, also set the remote URL so `git push` is authenticated.
  // This handles the case where the user passes an SSH URL for cloning but we
  // need HTTPS for pushing in a token-auth environment.
  if (token && repoUrl.startsWith('https://')) {
    execSync(`git remote set-url origin "${cloneUrl}"`, { cwd: REPO_DIR, stdio: 'pipe' });
  }

  console.log('Clone complete.\n');
}

/**
 * commit — Writes a code file and creates a git commit with a custom date.
 *
 * Inputs:
 *   folderName (string) — subfolder inside the repo, e.g. "1 Two Sum"
 *   fileName   (string) — the file to create, e.g. "1-two-sum.py"
 *   code       (string) — the actual source code to write
 *   message    (string) — the commit message
 *   timestamp  (string) — ISO 8601 date string of the original submission
 */
export function commit(folderName, fileName, code, message, timestamp) {
  const repoPath = getRepoPath();

  const folderPath = path.join(repoPath, folderName);
  if (!fs.existsSync(folderPath)) {
    fs.mkdirSync(folderPath, { recursive: true });
  }

  const filePath = path.join(folderPath, fileName);
  fs.writeFileSync(filePath, code, 'utf-8');

  const dateString = new Date(timestamp).toISOString();

  execSync('git add .', { cwd: repoPath, stdio: 'pipe' });

  execSync(`git commit --allow-empty --date="${dateString}" -m "${message}"`, {
    cwd:   repoPath,
    stdio: 'pipe',
    env: {
      ...process.env,
      GIT_COMMITTER_DATE: dateString,
    },
  });
}

/**
 * commitReadme — Writes README.md to the repo root and commits it.
 */
export function commitReadme(content) {
  const repoPath   = getRepoPath();
  const readmePath = path.join(repoPath, 'README.md');
  fs.writeFileSync(readmePath, content, 'utf-8');

  execSync('git add README.md', { cwd: repoPath, stdio: 'pipe' });

  try {
    execSync('git commit -m "📚 Update README — auto-generated by CodeSync"', {
      cwd:   repoPath,
      stdio: 'pipe',
    });
  } catch (err) {
    if (!err.message.includes('nothing to commit')) throw err;
  }
}

/**
 * push — Pushes all local commits to the remote repository, then cleans up.
 *
 * The remote URL already has the token embedded (set during init),
 * so no extra credentials are needed here.
 */
export function push() {
  const repoPath = getRepoPath();

  console.log('\nPushing all commits to remote...');
  execSync('git push', { cwd: repoPath, stdio: 'inherit' });
  console.log('Push complete!');

  console.log('Cleaning up local repo folder...');
  fs.rmSync(repoPath, { recursive: true, force: true });
  console.log('Cleanup done.\n');
}
